#!/usr/bin/env bash

# Enable Charon virtualenv
for venv_path in /opt/charon/venv/charon; do
  if [ -f $venv_path/bin/activate ]; then
    . $venv_path/bin/activate
  fi
done

# Run the requested Python command, using the interpreter from the path
exec python3 "$@"

